# Usa uma imagem base do Nginx
FROM nginx:latest

# Define o diretório de trabalho dentro do container
WORKDIR /usr/share/nginx/html

# Remove arquivos padrão do Nginx e copia seu projeto para o diretório do Nginx
RUN rm -rf ./*
COPY . .

# Expõe a porta 80 do container
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
